### ISSUE TITLE
Address already in use error

### ISSUE THREAD

**Issue by swotai** [brian-su/homebridge-sonos-so-simple#51]
**Describe The Bug:**

Got an "address already in use error" and the child bridge keep restarting.

**To Reproduce:**

Not sure how to reproduce. I have other services that's probably also using 4000 in another docker container.

**Expected behavior:**

**Logs:**

```
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at SonosListener.startListener (/homebridge/node_modules/homebridge-sonos-so-simple/node_modules/sonos/lib/events/adv-listener.js:67:25)
    at /homebridge/node_modules/homebridge-sonos-so-simple/node_modules/sonos/lib/events/adv-listener.js:101:12
    at new Promise (<anonymous>)
    at SonosListener.subscribeTo (/homebridge/node_modules/homebridge-sonos-so-simple/node_modules/sonos/lib/events/adv-listener.js:100:12)
    at Sonos.implicitListen (/homebridge/node_modules/homebridge-sonos-so-simple/node_modules/sonos/lib/sonos.js:70:21)
    at Sonos.emit (node:events:513:28)
    at _addListener (node:events:556:14)
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge name",
        "username": "xxx",
        "port": 51530,
        "pin": "xxx",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Garage",
            "username": "xxx",
            "password": "xxx",
            "batteryLowLevel": 15,
            "userInfoCacheTtl": 3600,
            "doorStatusStationaryCacheTtl": 30,
            "doorStatusTransitioningCacheTtl": 10,
            "doorStatusPollInterval": 60000,
            "logApiResponses": true,
            "showShared": false,
            "_bridge": {
                "username": "xxx",
                "port": 49921
            },
            "platform": "GenieAladdinConnect"
        },
        {
            "devices": [
                {
                    "api_key": "xxx",
                    "device_id": "xxx",
                    "name": "TV",
                    "ip": "tv_ip_addr",
                    "mac": "tv_mac",
                    "inputs": [
                        {
                            "type": "art",
                            "name": "Art Mode"
                        }
                    ]
                }
            ],
            "platform": "SamsungTizen"
        },
        {
            "muteSwitch": false,
            "soundbarsOnly": false,
            "roomNameAsName": false,
            "volume": "bulb",
            "volumeControlEndpoints": false,
            "preserveVolumeOnInputSwitch": false,
            "platform": "SonosSoSimplePlatform",
            "_bridge": {
                "username": "xxx",
                "port": 55273
            }
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.4.0
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 18.16.0
* **NPM Version**: 
* **Operating System**: Ubuntu + Docker

**Comment by brian-su** [comment]
Ok, that's a pain in the ass. The bug is actually coming from the Sonos package that I use to talk to the devices. It's hard coded to port 4000 meaning I can't really change it. 

The last version of the package was 3 years ago, so short of re-writing the entire Sonos package I'm not hopeful I'd be able to fix this. If you knew what was grabbing port 4000 you could try and get that to change port. 

Best I can probably do is push an update for my package to fail more gracefully. But it'll just have to crap out and say "port 4000 already in use, Sonos controls unavailable" :/

**Comment by swotai** [comment]
ah that sucks. Thanks!
